name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
          requireScope: false

      - name: Check for CHANGELOG update
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-changelog')"
        run: |
          if ! git diff --name-only origin/main...HEAD | grep -q "CHANGELOG.md"; then
            echo "Warning: CHANGELOG.md not updated. Add 'skip-changelog' label if intentional."
            # Don't fail, just warn
          fi

  size-check:
    name: Binary Size Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build base
        run: |
          make build
          BASE_SIZE=$(stat -f%z bin/warren 2>/dev/null || stat -c%s bin/warren)
          echo "BASE_SIZE=$BASE_SIZE" >> $GITHUB_ENV

      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Build PR
        run: |
          make build
          PR_SIZE=$(stat -f%z bin/warren 2>/dev/null || stat -c%s bin/warren)
          echo "PR_SIZE=$PR_SIZE" >> $GITHUB_ENV

      - name: Compare sizes
        run: |
          BASE_MB=$((BASE_SIZE / 1024 / 1024))
          PR_MB=$((PR_SIZE / 1024 / 1024))
          DIFF=$((PR_SIZE - BASE_SIZE))
          DIFF_MB=$((DIFF / 1024 / 1024))

          echo "Base binary size: ${BASE_MB}MB"
          echo "PR binary size: ${PR_MB}MB"
          echo "Size difference: ${DIFF_MB}MB"

          if [ $DIFF -gt 5242880 ]; then
            echo "Warning: Binary size increased by more than 5MB"
            echo "Please review if this increase is necessary."
          fi

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
